VIDEO_FOLDER: '/tmp/ECCV2022_Sign_Spotting_Challenge/CSLR_workspace/SignSpotting/data/TRACK2/PUBLIC/OSLWL_TEST_SET_VIDEOS'
ELAN_FOLDER: '/tmp/ECCV2022_Sign_Spotting_Challenge/CSLR_workspace/SignSpotting/data/TRACK2/PUBLIC/OSLWL_TEST_SET/eaf'
LABEL_EXPERIMENT: 'OSLWL/EXPERIMENTO_OSLWL_TEST_SET'
LABEL_EXPERIMENT_QUERIES: 'OSLWL/EXPERIMENTO_OSLWL_QUERY_TEST_SET'
BATCH_SIZE: 100
DEVICE_GPU: 0
FPS: 25

TYPE_KPS: 'C3_xyz'                    # C3_xyc, C3_xyz, C4_xyzc
TYPE_FEATURES: ['joints', 'bones']    # joints, bones, joints_motion, bones_motion


FOLDER_MODELS: 'config/model/track1_preprocessed_train/track1_400'
FOLDER_FILTER_MODELS: 'config/model/track1_preprocessed_train/track1_1000'


WINDOWS_SIZE: 10
WINDOWS_STRIDE: 1

PHASES_PREPARATION: [True, True]
# A1: python preprocess_video_playlist.py & python preparate_elan_files.py
# A2: python generate_kps.py & python generate_features.py

## Joints
FOLDER_Joints_DATA_SET: 'EXPERIMENTO_OSLWL_TEST_SET/B2_ISLR_output_RAW/out_global_average/joints_C3_xyz'
FOLDER_Joints_DATA_QUERY_SET: 'EXPERIMENTO_OSLWL_QUERY_TEST_SET/B2_ISLR_output_RAW/out_global_average/joints_C3_xyz'
#Bones
FOLDER_Bones_DATA_SET: 'EXPERIMENTO_OSLWL_TEST_SET/B2_ISLR_output_RAW/out_global_average/bones_C3_xyz'
FOLDER_Bones_DATA_QUERY_SET: 'EXPERIMENTO_OSLWL_QUERY_TEST_SET/B2_ISLR_output_RAW/out_global_average/bones_C3_xyz'

QUERY_LIMITS: '../data/clases_track2_TEST.csv'

PHASES_OP1: [True, True, True]
# B1: python generate_Windows.py
# B2: python generate_ISLR_output.py
# B3: python detect_queries_on_videos.py


EVALUATION: False  # E1
LABELS: '../data/OSLWL_TEST_SET_LABELS.txt'
VIS: False
METRIC: True
ELAN: False
THRESHOLD_IOU_MIN: 0.2
THRESHOLD_IOU_MAX: 0.8
THRESHOLD_IOU_STEP: 0.05
