# model
model: model.msg3d.Model
model_args:
  num_class: 60
  num_point: 53
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.mediapipe_bones.AdjMatrixGraph

device: 0

weights: ./config/model/pretrained_models/track1_400_train_bones.pt

